<script type="text/javascript" src="{{ asset('user/js/jquery-3.5.1.min.js')}}"></script>
<script type="text/javascript" src="{{ asset('user/js/jquery-migrate-3.3.1.min.js')}}"></script>
<script type="text/javascript" src="{{ asset('user/js/mmenu.min.js')}}"></script>
<script type="text/javascript" src="{{ asset('user/js/chosen.min.js')}}"></script>
<script type="text/javascript" src="{{ asset('user/js/slick.min.js')}}"></script>
<script type="text/javascript" src="{{ asset('user/js/rangeslider.min.js')}}"></script>
<script type="text/javascript" src="{{ asset('user/js/magnific-popup.min.js')}}"></script>
<script type="text/javascript" src="{{ asset('user/js/waypoints.min.js')}}"></script>
<script type="text/javascript" src="{{ asset('user/js/counterup.min.js')}}"></script>
<script type="text/javascript" src="{{ asset('user/js/jquery-ui.min.js')}}"></script>
<script type="text/javascript" src="{{ asset('user/js/tooltips.min.js')}}"></script>
<script type="text/javascript" src="{{ asset('user/js/custom.js')}}"></script>